name: Python application packaging

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  package:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: dl upx
      run: |
        python .github\getLatestUPX.py
        7z x upx.zip; mv upx-* upx

    - name: Package application with PyInstaller
      run: |
        pyinstaller --upx-dir upx AutoSubtitle.spec -y
        mv dist/AutoSubtitle ./
        cp -r fonts/ AutoSubtitle/
        cp readme.txt AutoSubtitle/使用说明.txt
        Compress-Archive -Path AutoSubtitle -DestinationPath AutoSubtitle.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: AutoSubtitle
        path: AutoSubtitle.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: TODO New Release
        draft: false
        prerelease: false

    - name: Upload Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "AutoSubtitle.zip"
        release_id: ${{ steps.create_release.outputs.id }}
        tags: true